const states = {
    hash: '167fa407df4583d2fd7b',
    version: '5.89.0',
    time: 90,
    builtAt: 1702392190101,
    publicPath: 'auto',
    outputPath: 'E:\\study\\mini-webpack\\dist',
    assetsByChunkName: { entry1: ['entry1.js'], entry2: ['entry2.js'] },
    assets: [
        {
            type: 'asset',
            name: 'entry1.js',
            size: 1634,
            emitted: false,
            comparedForEmit: true,
            cached: false,
            info: [Object],
            chunkNames: [Array],
            chunkIdHints: [],
            auxiliaryChunkNames: [],
            auxiliaryChunkIdHints: [],
            filteredRelated: undefined,
            related: {},
            chunks: [Array],
            auxiliaryChunks: [],
            isOverSizeLimit: false
        },
        {
            type: 'asset',
            name: 'entry2.js',
            size: 1634,
            emitted: false,
            comparedForEmit: true,
            cached: false,
            info: [Object],
            chunkNames: [Array],
            chunkIdHints: [],
            auxiliaryChunkNames: [],
            auxiliaryChunkIdHints: [],
            filteredRelated: undefined,
            related: {},
            chunks: [Array],
            auxiliaryChunks: [],
            isOverSizeLimit: false
        }
    ],
    filteredAssets: undefined,
    chunks: [
        {
            rendered: true,
            initial: true,
            entry: true,
            recorded: false,
            reason: undefined,
            size: 88,
            sizes: [Object: null prototype],
            names: [Array],
            idHints: [],
            runtime: [Array],
            files: [Array],
            auxiliaryFiles: [],
            hash: 'd33e25e3b5b666b45f7a',
            childrenByOrder: [Object: null prototype] {},
        id: 'entry1',
        siblings: [],
        parents: [],
        children: [],
        origins: [Array]
      },
    {
        rendered: true,
        initial: true,
        entry: true,
        recorded: false,
        reason: undefined,
        size: 88,
        sizes: [Object: null prototype],
        names: [Array],
        idHints: [],
        runtime: [Array],
        files: [Array],
        auxiliaryFiles: [],
        hash: '1e7aae8892ef98f17f3b',
        childrenByOrder: [Object: null prototype] { },
    id: 'entry2',
    siblings: [],
    parents: [],
    children: [],
    origins: [Array]
      }
    ],
modules: [
    {
        type: 'module',
        moduleType: 'javascript/auto',
        layer: null,
        size: 60,
        sizes: [Object],
        built: true,
        codeGenerated: true,
        buildTimeExecuted: false,
        cached: false,
        identifier: 'E:\\study\\mini-webpack\\src\\entry1.js',
        name: './src/entry1.js',
        nameForCondition: 'E:\\study\\mini-webpack\\src\\entry1.js',
        index: 0,
        preOrderIndex: 0,
        index2: 1,
        postOrderIndex: 1,
        cacheable: true,
        optional: false,
        orphan: false,
        dependent: undefined,
        issuer: null,
        issuerName: null,
        issuerPath: null,
        failed: false,
        errors: 0,
        warnings: 0,
        id: './src/entry1.js',
        issuerId: null,
        chunks: [Array],
        assets: [],
        reasons: [Array],
        filteredReasons: undefined,
        usedExports: null,
        providedExports: null,
        optimizationBailout: [],
        depth: 0
    },
    {
        type: 'module',
        moduleType: 'javascript/auto',
        layer: null,
        size: 60,
        sizes: [Object],
        built: true,
        codeGenerated: true,
        buildTimeExecuted: false,
        cached: false,
        identifier: 'E:\\study\\mini-webpack\\src\\entry2.js',
        name: './src/entry2.js',
        nameForCondition: 'E:\\study\\mini-webpack\\src\\entry2.js',
        index: 2,
        preOrderIndex: 2,
        index2: 2,
        postOrderIndex: 2,
        cacheable: true,
        optional: false,
        orphan: false,
        dependent: undefined,
        issuer: null,
        issuerName: null,
        issuerPath: null,
        failed: false,
        errors: 0,
        warnings: 0,
        id: './src/entry2.js',
        issuerId: null,
        chunks: [Array],
        assets: [],
        reasons: [Array],
        filteredReasons: undefined,
        usedExports: null,
        providedExports: null,
        optimizationBailout: [],
        depth: 0
    },
    {
        type: 'module',
        moduleType: 'javascript/auto',
        layer: null,
        size: 28,
        sizes: [Object],
        built: true,
        codeGenerated: true,
        buildTimeExecuted: false,
        cached: false,
        identifier: 'E:\\study\\mini-webpack\\src\\title.js',
        name: './src/title.js',
        nameForCondition: 'E:\\study\\mini-webpack\\src\\title.js',
        index: 1,
        preOrderIndex: 1,
        index2: 0,
        postOrderIndex: 0,
        cacheable: true,
        optional: false,
        orphan: false,
        dependent: undefined,
        issuer: 'E:\\study\\mini-webpack\\src\\entry1.js',
        issuerName: './src/entry1.js',
        issuerPath: [Array],
        failed: false,
        errors: 0,
        warnings: 0,
        id: './src/title.js',
        issuerId: './src/entry1.js',
        chunks: [Array],
        assets: [],
        reasons: [Array],
        filteredReasons: undefined,
        usedExports: null,
        providedExports: null,
        optimizationBailout: [Array],
        depth: 1
    }
],
    filteredModules: undefined,
        entrypoints: [Object: null prototype] {
    entry1: {
        name: 'entry1',
            chunks: [Array],
                assets: [Array],
                    filteredAssets: 0,
                        assetsSize: 1634,
                            auxiliaryAssets: [],
                                filteredAuxiliaryAssets: 0,
                                    auxiliaryAssetsSize: 0,
                                        children: [Object: null prototype] { },
        childAssets: [Object: null prototype] { },
        isOverSizeLimit: false
    },
    entry2: {
        name: 'entry2',
            chunks: [Array],
                assets: [Array],
                    filteredAssets: 0,
                        assetsSize: 1634,
                            auxiliaryAssets: [],
                                filteredAuxiliaryAssets: 0,
                                    auxiliaryAssetsSize: 0,
                                        children: [Object: null prototype] { },
        childAssets: [Object: null prototype] { },
        isOverSizeLimit: false
    }
},
namedChunkGroups: [Object: null prototype] {
    entry1: {
        name: 'entry1',
            chunks: [Array],
                assets: [Array],
                    filteredAssets: 0,
                        assetsSize: 1634,
                            auxiliaryAssets: [],
                                filteredAuxiliaryAssets: 0,
                                    auxiliaryAssetsSize: 0,
                                        children: [Object: null prototype] { },
        childAssets: [Object: null prototype] { },
        isOverSizeLimit: false
    },
    entry2: {
        name: 'entry2',
            chunks: [Array],
                assets: [Array],
                    filteredAssets: 0,
                        assetsSize: 1634,
                            auxiliaryAssets: [],
                                filteredAuxiliaryAssets: 0,
                                    auxiliaryAssetsSize: 0,
                                        children: [Object: null prototype] { },
        childAssets: [Object: null prototype] { },
        isOverSizeLimit: false
    }
},
errors: [],
    errorsCount: 0,
        warnings: [],
            warningsCount: 0,
                children: []
  }